### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by serna01** [suchetanrs/ORB-SLAM3-ROS2-Docker#3] opened 2024-05-07 09:43 UTC
I run: ros2 launch orb_slam3_ros2_wrapper unirobot.launch.py

and get the following output:
``INFO] [launch]: All log files can be found below /root/.ros/log/2024-05-07-11-37-56-223309-asm-1523
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rgbd-1]: process started with pid [1524]
[rgbd-1] Interface constructor started
[rgbd-1] 
[rgbd-1] ORB-SLAM3 Copyright (C) 2017-2020 Carlos Campos, Richard Elvira, Juan J. Gómez, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
[rgbd-1] ORB-SLAM2 Copyright (C) 2014-2016 Raúl Mur-Artal, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
[rgbd-1] This program comes with ABSOLUTELY NO WARRANTY;
[rgbd-1] This is free software, and you are welcome to redistribute it
[rgbd-1] under certain conditions. See LICENSE.txt.
[rgbd-1] 
[rgbd-1] Input sensor was set to: RGB-D
[rgbd-1] 
[rgbd-1] Loading ORB Vocabulary. This could take a while...
[rgbd-1] Vocabulary loaded!
[rgbd-1] 
[rgbd-1] Initialization of Atlas from scratch 
[rgbd-1] Creation of new map with id: 0
[rgbd-1] Creation of new map with last KF id: 0
[rgbd-1] Seq. Name: 
[rgbd-1] 
[rgbd-1] Camera Parameters: 
[rgbd-1] - Camera: Pinhole
[rgbd-1] - Image scale: 1
[rgbd-1] - fx: 528.434
[rgbd-1] - fy: 528.434
[rgbd-1] - cx: 320.5
[rgbd-1] - cy: 240.5
[rgbd-1] - k1: 0
[rgbd-1] - k2: 0
[rgbd-1] - p1: 0
[rgbd-1] - p2: 0
[rgbd-1] - k3: 0
[rgbd-1] - fps: 30
[rgbd-1] - color order: BGR (ignored if grayscale)
[rgbd-1] 
[rgbd-1] Depth Threshold (Close/Far Points): 2.80073
[rgbd-1] 
[rgbd-1] ORB Extractor Parameters: 
[rgbd-1] - Number of Features: 1250
[rgbd-1] - Scale Levels: 8
[rgbd-1] - Scale Factor: 1.2
[rgbd-1] - Initial Fast Threshold: 20
[rgbd-1] - Minimum Fast Threshold: 7
[rgbd-1] There are 1 cameras in the atlas
[rgbd-1] Camera 0 is pinhole
[rgbd-1] INIT COMPLETE
[rgbd-1] Interface constructor complete
[rgbd-1] ============================ 
[rgbd-1] [INFO] [1715074681.161079568] [scout_2.ORB_SLAM3_RGBD_ROS2]: CONSTRUCTOR END!
[rgbd-1] 
[rgbd-1] (ORB-SLAM3: Current Frame:1524): dbind-WARNING **: 11:38:01.854: Couldn't connect to accessibility bus: Failed to connect to socket /run/user/1000/at-spi/bus_0: No such file or directory
[rgbd-1] Gtk-Message: 11:38:01.911: Failed to load module "canberra-gtk-module"
[rgbd-1] Gtk-Message: 11:38:01.914: Failed to load module "canberra-gtk-module"
[rgbd-1] Starting the Viewer``

**Comment by suchetanrs** [comment] 2024-05-07 09:49
Hi, thanks for your ticket.
Could you please let me know if the viewer opens up after running this command? The viewer here are two windows which show the map and the actively tracked points on the image.

**Comment by serna01** [comment] 2024-05-07 11:01
Thanks for the quick response.
Two viewers open, one is completely black and has a message saying waiting for images, and the other is just empty with a kind of green camera view model I would assume.

**Comment by suchetanrs** [comment] 2024-05-08 10:24
Thank you for your reply.
This is the expected behaviour. The wrapper is waiting for images on the required topic in this case.
I believe the topic name is ```/<node_namespace> + "camera/image_raw"```.
Once the messages are received on this topic, the tracking will begin. However, please note that the default camera parameter file will not work with your own images.
Be sure to get your calibration parameters and put it in a file similar to [this](https://github.com/suchetanrs/ORB-SLAM3-ROS2-Docker/blob/master/orb_slam3_ros2_wrapper/params/scout_v2_rgbd.yaml).
If this does not work, I will upload a simulation container soon so you could test it with that :)

**Comment by suchetanrs** [comment] 2024-08-31 18:19
Hey, the simulation container is uploaded and it seems to work fine.
I will close this issue now. If you face the same problem still, feel free to re-open this.

**Closed by suchetanrs** 2024-08-31 18:19 UTC

**Comment by suchetanrs** [comment] 2024-09-02 13:32
Hi,

In the ros2 wrapper container, please check the frequency of the messages received on the topic. You can do this by ```ros2 topic hz <topic name>```

Please try it for /robot_0/rgb_camera and /robot_0/depth_camera

**Comment by serna01** [comment] 2024-09-02 13:39
On the wrapper, still getting only the black window for the frame and the white one for the map:

`ros2 topic hz /robot_0/rgb_camera`

```
average rate: 8.514
	min: 0.066s max: 0.489s std dev: 0.12086s window: 13
average rate: 10.483
	min: 0.063s max: 0.489s std dev: 0.08776s window: 27
average rate: 9.936
	min: 0.063s max: 0.489s std dev: 0.09379s window: 36
average rate: 10.087
	min: 0.063s max: 0.489s std dev: 0.08708s window: 47
average rate: 9.819
	min: 0.063s max: 0.489s std dev: 0.08864s window: 56
average rate: 10.098
	min: 0.063s max: 0.489s std dev: 0.08240s window: 68
```

`ros2 topic hz /robot_0/depth_camera`

```
average rate: 6.291
	min: 0.068s max: 0.416s std dev: 0.11966s window: 7
average rate: 5.393
	min: 0.068s max: 0.479s std dev: 0.13750s window: 12
average rate: 7.674
	min: 0.064s max: 0.479s std dev: 0.11243s window: 25
average rate: 8.125
	min: 0.064s max: 0.479s std dev: 0.10031s window: 35
average rate: 8.047
	min: 0.064s max: 0.550s std dev: 0.11353s window: 43
average rate: 7.723
	min: 0.061s max: 0.559s std dev: 0.12380s window: 51
```

**Comment by suchetanrs** [comment] 2024-09-02 13:46
Can you also please share your rgbd parameter file?
You should find it within the wrapper's package

**Comment by serna01** [comment] 2024-09-02 13:50
`ros2 node list`
```
WARNING: Be aware that are nodes in the graph that share an exact name, this can have unintended side effects.
/clock_bridge
/image_bridge0
/image_bridge0
/parameter_bridge0
/robot_0/teleop_twist_keyboard
/robot_state_publisher0
/scout_2/ORB_SLAM3_RGBD_ROS2
/scout_2/transform_listener_impl_59e4e55b4070
```

~/colcon_ws/src/orb_slam3_ros2_wrapper/params# nano rgbd-ros-params.yaml 

```
ORB_SLAM3_RGBD_ROS2:
  ros__parameters:
    robot_base_frame: base_footprint
    global_frame: map
    odom_frame: odom
    robot_x: 0.0
    robot_y: 0.0
    visualization: true
    ros_visualization: false
    no_odometry_mode: false
```

**Comment by suchetanrs** [comment] 2024-09-02 13:56
It seems like you are not on the latest commit. There have been several updates since the version you're running. Can you re-clone and rebuild the wrapper? It should work then.
You don't have to rebuild the simulation container.

**Comment by serna01** [comment] 2024-09-02 14:33
It works now! Thanks

**Comment by suchetanrs** [comment] 2024-09-02 14:40
Awesome!
